package org.openspg.idea.schema.psi.impl;

import com.intellij.psi.tree.TokenSet;
import org.openspg.idea.schema.psi.SchemaTypes;


public interface BasicElementTypes extends SchemaTypes {

    TokenSet BASIC_KEYWORD_BIT_SET = TokenSet.create(
            AUTORELATE_KEYWORD, BASIC_TYPE_KEYWORD, CONCEPT_TYPE_KEYWORD, CONSTRAINT_KEYWORD, DESC_KEYWORD, ENTITY_TYPE_KEYWORD,
            EVENT_TYPE_KEYWORD, FLOAT_KEYWORD, HYPERNYMP_PREDICATE_KEYWORD, INDEX_KEYWORD, INTEGER_KEYWORD, IS_A_KEYWORD,
            LOCATE_AT_KEYWORD, MANNER_OF_KEYWORD, MULTI_VALUE_KEYWORD, NAMESPACE_KEYWORD, NOT_NULL_KEYWORD, PROPERTIES_KEYWORD,
            REGULAR_KEYWORD, RELATIONS_KEYWORD, RULE_KEYWORD, SPREADABLE_KEYWORD, STANDARD_TYPE_KEYWORD, TEXT_AND_VECTOR_KEYWORD,
            TEXT_KEYWORD, VECTOR_KEYWORD
    );

    TokenSet BASIC_OPERATION_BIT_SET = TokenSet.create(
            RIGHT_ARROW, LPARENTH, RPARENTH, COMMA, HASH, COLON, DOT, DOUBLE_LBRACKET, DOUBLE_RBRACKET
    );

    TokenSet BASIC_STRING_LITERALS = TokenSet.create(STRING_LITERAL);

}
